### ISSUE TITLE
最新版本女巫环节无法正常执行

### ISSUE THREAD

**Issue by TheFlareStar** [LemonNeko2452/WolfKill#7]
后台报错这个
java.lang.IndexOutOfBoundsException: Index -891106412 out of bounds for length 5

**Comment by LemonNeko2452** [comment]
请详细描述无法正常执行的现象，后台报错把所有报错内容展示出来

**Comment by TheFlareStar** [comment]
[1.txt](https://github.com/LemonNeko2452/WolfKill/files/10413211/1.txt)

**Comment by TheFlareStar** [comment]
就是不会主动私聊玩家了，发指令也没反应，之前的环节都正常的

**Comment by LemonNeko2452** [comment]
你群私聊开了吗

**Comment by LemonNeko2452** [comment]
解决了，你试试最新版

**Comment by TheFlareStar** [comment]
还有个小问题，投票出局人的时候不会提示是谁被出局
![image](https://user-images.githubusercontent.com/91410099/212446798-272f7377-7444-46a3-aed9-849dc8d907c8.png)

**Comment by TheFlareStar** [comment]
然后看后台发现有这么一段报错
```
2023-01-14 10:25:25 E/ExternalResourceLeakObserver: A resource leak occurred, use ExternalResource.close to avoid it!! (holder=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder@3eb940a0)
net.mamoe.mirai.internal.utils.ExternalResourceLeakObserver$ExternalResourceCreateStackTrace
        at java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
        at net.mamoe.mirai.internal.utils.ExternalResourceHolder.<init>(ExternalResourceImpls.kt:80)
        at net.mamoe.mirai.internal.utils.ExternalResourceImplByFile$ResourceHolder.<init>(ExternalResourceImpls.kt:119)
        at net.mamoe.mirai.internal.utils.ExternalResourceImplByFile.<init>(ExternalResourceImpls.kt:126)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create(ExternalResource.kt:291)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create$default(ExternalResource.kt:287)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create(ExternalResource.kt:270)
        at net.mamoe.mirai.utils.ExternalResource$Companion.create$default(ExternalResource.kt:268)
        at WolfKill-0.1.9.mirai2.jar//work.anqi.command.Go.handle(Go.kt:111)
        at WolfKill-0.1.9.mirai2.jar//work.anqi.command.Go$handle$1.invokeSuspend(Go.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by LemonNeko2452** [comment]
更新了

**Comment by abcabl** [comment]
猎人被狼人刀了之后，为什么不会触发他的技能啊？

**Comment by FurLC** [comment]
在多个人说go后会发多次身份，然后就不开始了
